insert into guests (guest_id, first_name, last_name, email_address, street_address, city, province, country, postal_code, payment) values ('c3540a89-cb47-4c96-888e-ff96708db4d8', 'Alick', 'Ucceli', 'aucceli0@dot.gov', '73 Shoshone Road', 'Barraute', 'Québec', 'Canada', 'P0M 2T6', 'CreditCard');
insert into guests (guest_id, first_name, last_name, email_address, street_address, city, province, country, postal_code, payment) values ('dd1ab8b0-ab17-4e03-b70a-84caa3871606', 'Ricky', 'Presslie', 'rpresslie1@domainmarket.com', '24 Dorton Circle', 'Notre-Dame-des-Prairies', 'Québec', 'Canada', 'K6V 3J2', 'DebitCard');
insert into guests (guest_id, first_name, last_name, email_address, street_address, city, province, country, postal_code, payment) values ('ba6c3e76-366e-44bb-8279-b41dc32dc456', 'Allx', 'Cholmondeley', 'acholmondeley2@weibo.com', '61 Farragut Street', 'Senneterre', 'Québec', 'Canada', 'L0P 1J8', 'CreditCard');
insert into guests (guest_id, first_name, last_name, email_address, street_address, city, province, country, postal_code, payment) values ('45772446-62f4-4ccb-b3f4-9393c186fa43', 'Gaspar', 'Russi', 'grussi3@un.org', '3612 Del Mar Terrace', 'Sainte-Marthe-sur-le-Lac', 'Québec', 'Canada', 'H9K 0W3' , 'CreditCard');
insert into guests (guest_id, first_name, last_name, email_address, street_address, city, province, country, postal_code, payment) values ('30a4e2e3-fe9d-4903-bd23-b0a72b6c4ced', 'Hillard', 'Heamus', 'hheamus4@va.gov', '809 Blue Bill Park Park', 'Cowansville', 'Québec', 'Canada', 'J2K P4X', 'Cash');
insert into guests (guest_id, first_name, last_name, email_address, street_address, city, province, country, postal_code, payment) values ('2bec7ec2-fe40-474f-a8cd-612f7790d24f', 'Darrin', 'Cadd', 'dcadd5@ning.com', '9 Cambridge Road', 'Havre-Saint-Pierre', 'Québec', 'Canada', 'H4R 1R9', 'CreditCard');
insert into guests (guest_id, first_name, last_name, email_address, street_address, city, province, country, postal_code, payment) values ('6b2214d8-8d17-42f3-82bd-1b9264f19c64', 'Susana', 'Maxfield', 'smaxfield6@themeforest.net', '4509 Mifflin Road', 'Acton Vale', 'Québec', 'Canada', 'G0E N6E','CreditCard' );
insert into guests (guest_id, first_name, last_name, email_address, street_address, city, province, country, postal_code, payment) values ('a11014c8-85bc-4f8a-b627-7dfd645764ce', 'Elias', 'Plaxton', 'eplaxton7@house.gov', '382 Dorton Terrace', 'London', 'Ontario', 'Canada', 'N6C 2E4', 'Cash');
insert into guests (guest_id, first_name, last_name, email_address, street_address, city, province, country, postal_code, payment) values ('13526a90-506f-4981-a9da-06ba21fc610b', 'Ralina', 'Sussex', 'rsussex8@nymag.com', '624 Gale Alley', 'Waterloo', 'Ontario', 'Canada', 'N2L 7K8', 'CreditCard');

